version: "3"

services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    command: "air -c .air.toml"
    ports:
      - 4100:4100
    volumes:
      - ./backend:/app/go/backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: local
      MYSQL_PASSWORD: local
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ./var/mysql:/var/lib/mysql
    command: --general-log=true --general-log-file=/var/lib/mysql/general.log --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
