version: "3.9"

services:
  api:
    depends_on:
      - db
    build:
      context: backend
      dockerfile: Dockerfile
    command: "air -c .air.ham_api.toml"
    env_file:
      - ./backend/.env
    ports:
      - 4100:4100
    volumes:
      - ./backend:/app

  trader:
    depends_on:
      - db
    build:
      context: backend
      dockerfile: Dockerfile
    command: "air -c .air.ham_trader.toml"
    env_file:
      - ./backend/.env
    tty: true
    stdin_open: true
    volumes:
      - ./backend:/app

  backend_cli:
    depends_on:
      - db
    build:
      context: backend
      dockerfile: Dockerfile
    command: "ash"
    env_file:
      - ./backend/.env
    profiles:
      - backend_cli
    volumes:
      - ./backend:/app

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: local
      MYSQL_PASSWORD: local
      MYSQL_DATABASE: hamster
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ./var/mysql:/var/lib/mysql
    command: --general-log=true --general-log-file=/var/lib/mysql/general.log --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
